import Navigation from '@/components/Navigation'

import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My first webpage',
  description: 'Generated by create next app',
  keywords:'next,react,app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Navigation />
        {children}</body>
    </html>
  )
}
