
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My first webpage',
  description: 'Generated by create next app',
  keywords:'next,react,app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>navigation</h1>
        <ul>
          <li>
              <a href="/">Home</a>
          </li>
          <li>
              <a href="/about ">About</a>
          </li>
          <li>
              <a href="/services">Services</a>
          </li>
        </ul>
        {children}</body>
    </html>
  )
}
